[package]
name = "dbus-marshal"
version.workspace = true
edition.workspace = true

[workspace]
resolver = "3"
members = ["macros"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
dbus-marshal-macros = { path = "macros/", version = "0.1.0" }
static_assertions = "1.1.0"
thiserror = { version = "2.0.18", default-features = false }

[features]
default = ["alloc"]
alloc = []
